version: "3.8"
services:
  app:
    <<: *app-service
    build:
      target: dev
      args:
        - BUNDLE_DEPLOYMENT=false
        - BUNDLE_WITH=development:test
    command: bundle exec guard --no-interactions 
    environment:
      - PUMA_WORKERS=0
      - RAILS_DEVELOPMENT_HOSTS=${APP_HOST_NAME}.${APP_DOMAIN}
    ports:
      - 1234:1234
      - 26162:26162
    volumes:
      - code:/app

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      mode: "two-way-resolved"
    code:
      alpha: "./base"
      beta: "volume://code"

