
services:
  app:
    <<: *app-service
    build:
      target: dev
      args:
        - BUNDLE_DEPLOYMENT=false
        - BUNDLE_WITH=development:test
    command: bundle exec guard --no-interactions 
    environment:
      - PUMA_WORKERS=0
      - RAILS_DEVELOPMENT_HOSTS=${APP_HOST_NAME}.${APP_DOMAIN}
    volumes:
      - code:/app

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "./base"
      beta: "volume://code"
