version: "3.8"
services:
  app:
    build:
      target: dev
    command: bundle exec guard --no-interactions 
    environment:
      - RACK_ENV=development
      - PUMA_WORKERS=0
      - RAILS_DEVELOPMENT_HOSTS=${APP_NAME}.local.${APP_DOMAIN}
    volumes:
      - ./base:/app
    labels:
      - joyride.host.name=${APP_NAME}.local.${APP_DOMAIN}

