version: "3.8"
services:
  app:
    networks:
      - default
    depends_on:
      - redis
      - memcached

  sidekiq:
    image: ${DOCKER_NAMESPACE:-ilude}/${APP_NAME}-${DEPLOY_STAGE:-production}
    container_name: ${APP_NAME}-sidekiq
    command: foreman start
    networks:
      - default
    depends_on:
      - redis
    environment:
      - MALLOC_ARENA_MAX=2 # https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/

  redis:
    image: bitnami/redis
    hostname: redis
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    mem_limit: 1g
    command: /opt/bitnami/scripts/redis/run.sh --loglevel ${REDIS_LOG_LEVEL:-notice}
    networks:
      - default
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitnami
  
  memcached:
    image: bitnami/memcached
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    mem_limit: 200m
    networks:
      - default

networks:
  default:

volumes:
  redis:
    external: false # false means docker compose will control its creation
  
