version: "3.8"
services:
  scheduler:
    extends:
      file: docker-compose.common.yml
      service: app
    build:
      target: prod
    image: ilude/${APP_NAME}-scheduler
    command: bundle exec rake scheduler
    container_name: ${APP_NAME}-scheduler 