version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - BUNDLE_DEPLOYMENT=true
        - BUNDLE_WITHOUT=development:test
    image: ilude/${APP_NAME}-${DEPLOY_STAGE:-production}
    hostname: ${APP_NAME}-${DEPLOY_STAGE:-production}
    container_name: ${APP_NAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RAILS_ENV=${ENV_CONTEXT}
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.enable=true