version: "3.8"
services:
  app:
    extends:
      file: docker-compose.common.yml
      service: app
    build:
      target: dev
      args:
        - BUNDLE_DEPLOYMENT=false
        - BUNDLE_WITH=development:test
    command: bundle exec guard --no-interactions 
    environment:
      - PUMA_WORKERS=0
      - RAILS_DEVELOPMENT_HOSTS=${APP_NAME}.local.${APP_DOMAIN}
    volumes:
      - code:/app
    labels:
      - joyride.host.name=${APP_NAME}.local.${APP_DOMAIN}

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "./base"
      beta: "volume://code"
