version: "3.8"
services:
  app:
    build:
      target: dev
      args: 
        - BUNDLE_ARGS=
    #user: ${PUID}:${PGID}
    command: bundle exec guard --no-interactions 
    ports:
      - 3000:3000
    environment:
      - RACK_ENV=development
      - PUMA_WORKERS=0
      - RAILS_DEVELOPMENT_HOSTS=${APP_NAME}.${APP_DOMAIN}
    volumes:
      - ./base:/app

